export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const RECEIVE_GROUP_ANNOUNCEMENT = 'RECEIVE_GROUPANNOUNCEMENT';
